version: '3.8'

services:
  mind-as-engine-frontend:
    container_name: mind-as-engine-frontend
    image: mind-as-engine-frontend
    build:
      context: ./frontend
    depends_on:
      - mind-as-engine-backend
    ports:
      - '3000:3000'
    networks:
      - 'frontend'
      - 'backend'

  mind-as-engine-backend:
    container_name: mind-as-engine-backend
    image: mind-as-engine-backend
    build:
      context: ./backend
    depends_on:
      - mind-as-engine-database
    env_file: environment.env
    volumes:
      - /home/mindasengine/res:/home/mindasengine/images
    ports:
      - '1337:1337'
    networks:
      - 'backend'

  mind-as-engine-database:
    container_name: mind-as-engine-database
    image: postgres:14-alpine3.18
    build:
      context: .
    env_file: environment.env
    volumes:
      - /home/mindasengine/pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - '5555:5432'
    networks:
      - 'backend'

  twg-proxy:
    image: valian/docker-nginx-auto-ssl
    restart: on-failure
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ssl_data:/etc/resty-auto-ssl
    env_file:
      - ./environment.env
  
    networks:
      - proxy
      - frontend
      - backend

networks:
  proxy:
    name: proxy_network
  frontend:
    name: frontend_network
  backend:
    name: backend_network